name: "HEU Auto Checkin"

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

env:
  RUN_ENV: 'prod'
  TZ: 'Asia/Shanghai'

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run checkin
        env:
          accounts: ${{ secrets.ACCOUNTS }}
        run: |
          python -m pip install --upgrade pip
          pip install pyppeteer
          pyppeteer-install
          echo $accounts | python3 checkin.py
